# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#

  # movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
  # Character.create(name: 'Luke', movie: movies.first)


# レディース
lady = MainCategory.create(main_name: "レディース")
lady_tops = lady.children.create(main_name: "トップス")
lady_tops.children.create([{main_name: "Tシャツ/カットソー(半袖/袖なし)"},{main_name: "Tシャツ/カットソー(七分/長袖)"},{main_name: "シャツ/ブラウス(半袖/袖なし)"},{main_name: "シャツ/ブラウス(七分/長袖)"},{main_name: "ポロシャツ"},{main_name: "キャミソール"},{main_name: "タンクトップ"},{main_name: "ホルターネック"},{main_name: "ニット/セーター"},{main_name: "チュニック"},{main_name: "カーディガン/ボレロ"},{main_name: "アンサンブル"},{main_name: "ベスト/ジレ"},{main_name: "パーカー"},{main_name: "トレーナー/スウェット"},{main_name: "ベアトップ/チューブトップ"},{main_name: "ジャージ"},{main_name: "その他"}])
lady_jacket = lady.children.create(main_name: "ジャケット/アウター")
lady_jacket.children.create([{main_name: "テーラードジャケット"},{main_name: "ノーカラージャケット"},{main_name: "Gジャン/デニムジャケット"},{main_name: "レザージャケット"},{main_name: "ダウンジャケット"},{main_name: "ライダースジャケット"},{main_name: "ミリタリージャケット"},{main_name: "ダウンベスト"},{main_name: "ジャンパー/ブルゾン"},{main_name: "ポンチョ"},{main_name: "ロングコート"},{main_name: "トレンチコート"},{main_name: "ダッフルコート"},{main_name: "ピーコート"},{main_name: "チェスターコート"},{main_name: "モッズコート"},{main_name: "スタジャン"},{main_name: "毛皮/ファーコート"},{main_name: "スプリングコート"},{main_name: "スカジャン"},{main_name: "その他"}])
lady_pants = lady.children.create(main_name: "パンツ")
lady_pants.children.create([{main_name: "デニム/ジーンズ"},{main_name: "ショートパンツ"},{main_name: "カジュアルパンツ"},{main_name: "ハーフパンツ"},{main_name: "チノパン"},{main_name: "ワークパンツ/カーゴパンツ"},{main_name: "クロップドパンツ"},{main_name: "サロペット/オーバーオール"},{main_name: "オールインワン"},{main_name: "サルエルパンツ"},{main_name: "ガウチョパンツ"},{main_name: "その他"}])
lady_skirt = lady.children.create(main_name: "スカート")
lady_skirt.children.create([{main_name: "ミニスカート"},{main_name: "ひざ丈スカート"},{main_name: "ロングスカート"},{main_name: "キュロット"},{main_name: "その他"}])
lady_dress = lady.children.create(main_name: "ワンピース")
lady_dress.children.create([{main_name: "ミニワンピース"},{main_name: "ひざ丈ワンピース"},{main_name: "ロングワンピース"},{main_name: "その他"}])
lady_shoes = lady.children.create(main_name: "靴")
lady_shoes.children.create([{main_name: "ハイヒール/パンプス"},{main_name: "ブーツ"},{main_name: "サンダル"},{main_name: "スニーカー"},{main_name: "ミュール"},{main_name: "モカシン"},{main_name: "ローファー/革靴"},{main_name: "フラットシューズ/バレエシューズ"},{main_name: "長靴/レインシューズ"},{main_name: "その他"}])
lady_pajamas = lady.children.create(main_name: "ルームウェア/パジャマ")
lady_pajamas.children.create([{main_name: "パジャマ"},{main_name: "ルームウェア"}])
lady_legwear = lady.children.create(main_name: "レッグウェア")
lady_legwear.children.create([{main_name: "ソックス"},{main_name: "スパッツ/レギンス"},{main_name: "ストッキング/タイツ"},{main_name: "レッグウォーマー"},{main_name: "その他"}])
lady_hat = lady.children.create(main_name: "帽子")
lady_hat.children.create([{main_name: "ニットキャップ/ビーニー"},{main_name: "ハット"},{main_name: "ハンチング/ベレー帽"},{main_name: "キャップ"},{main_name: "キャスケット"},{main_name: "麦わら帽子"},{main_name: "その他"}])
lady_bag = lady.children.create(main_name: "バッグ")
lady_bag.children.create([{main_name: "ハンドバッグ"},{main_name: "トートバッグ"},{main_name: "エコバッグ"},{main_name: "リュック/バックパック"},{main_name: "ボストンバッグ"},{main_name: "スポーツバッグ"},{main_name: "ショルダーバッグ"},{main_name: "クラッチバッグ"},{main_name: "ポーチ/バニティ"},{main_name: "ボディバッグ/ウェストバッグ"},{main_name: "マザーズバッグ"},{main_name: "メッセンジャーバッグ"},{main_name: "ビジネスバッグ"},{main_name: "旅行用バッグ/キャリーバッグ"},{main_name: "ショップ袋"},{main_name: "和装用バッグ"},{main_name: "かごバッグ"},{main_name: "その他"}])
lady_jewelry = lady.children.create(main_name: "アクセサリー")
lady_jewelry.children.create([{main_name: "ネックレス"},{main_name: "ブレスレット"},{main_name: "バングル/リストバンド"},{main_name: "リング"},{main_name: "ピアス(片耳用)"},{main_name: "ピアス(両耳用)"},{main_name: "イヤリング"},{main_name: "アンクレット"},{main_name: "ブローチ/コサージュ"},{main_name: "チャーム"},{main_name: "その他"}])
lady_hair_accessory = lady.children.create(main_name: "ヘアアクセサリー")
lady_hair_accessory.children.create([{main_name: "ヘアゴム/シュシュ"},{main_name: "ヘアバンド/カチューシャ"},{main_name: "ヘアピン"},{main_name: "その他"}])
lady_accessories = lady.children.create(main_name: "小物")
lady_accessories.children.create([{main_name: "長財布"},{main_name: "折り財布"},{main_name: "コインケース/小銭入れ"},{main_name: "名刺入れ/定期入れ"},{main_name: "キーケース"},{main_name: "キーホルダー"},{main_name: "手袋/アームカバー"},{main_name: "ハンカチ"},{main_name: "ベルト"},{main_name: "マフラー/ショール"},{main_name: "ストール/スヌード"},{main_name: "バンダナ/スカーフ"},{main_name: "ネックウォーマー"},{main_name: "サスペンダー"},{main_name: "サングラス/メガネ"},{main_name: "モバイルケース/カバー"},{main_name: "手帳"},{main_name: "イヤマフラー"},{main_name: "傘"},{main_name: "レインコート/ポンチョ"},{main_name: "ミラー"},{main_name: "タバコグッズ"},{main_name: "その他"}])
lady_clock = lady.children.create(main_name: "時計")
lady_clock.children.create([{main_name: "腕時計(アナログ)"},{main_name: "腕時計(デジタル)"},{main_name: "ラバーベルト"},{main_name: "レザーベルト"},{main_name: "金属ベルト"},{main_name: "その他"}])
lady_wig = lady.children.create(main_name: "ウィッグ/エクステ")
lady_wig.children.create([{main_name: "前髪ウィッグ"},{main_name: "ロングストレート"},{main_name: "ロングカール"},{main_name: "ショートストレート"},{main_name: "ショートカール"},{main_name: "その他"}])
lady_swimsuit = lady.children.create(main_name: "浴衣/水着")
lady_swimsuit.children.create([{main_name: "浴衣"},{main_name: "着物"},{main_name: "振袖"},{main_name: "長襦袢/半襦袢"},{main_name: "水着セパレート"},{main_name: "水着ワンピース"},{main_name: "水着スポーツ用"},{main_name: "その他"}])
lady_suit = lady.children.create(main_name: "スーツ/フォーマル/ドレス")
lady_suit.children.create([{main_name: "スカートスーツ上下"},{main_name: "パンツスーツ上下"},{main_name: "ドレス"},{main_name: "パーティーバッグ"},{main_name: "シューズ"},{main_name: "ウェディング"},{main_name: "その他"}])
lady_maternity = lady.children.create(main_name: "マタニティ")
lady_maternity.children.create([{main_name: "トップス"},{main_name: "アウター"},{main_name: "インナー"},{main_name: "ワンピース"},{main_name: "パンツ/スパッツ"},{main_name: "スカート"},{main_name: "パジャマ"},{main_name: "授乳服"},{main_name: "その他"}])
lady_other= lady.children.create(main_name: "その他")
lady_other.children.create([{main_name: "コスプレ"},{main_name: "下着"},{main_name: "その他"}])


# メンズ
men = MainCategory.create(main_name: "メンズ")
men_tops = men.children.create(main_name: "トップス")
men_tops.children.create([{main_name: "Tシャツ/カットソー(半袖/袖なし)"},{main_name: "Tシャツ/カットソー(七分/長袖)"},{main_name: "シャツ"},{main_name: "ポロシャツ"},{main_name: "タンクトップ"},{main_name: "ニット/セーター"},{main_name: "パーカー"},{main_name: "カーディガン"},{main_name: "スウェット"},{main_name: "ジャージ"},{main_name: "ベスト"},{main_name: "その他"}])
men_jacket = men.children.create(main_name: "ジャケット/アウター")
men_jacket.children.create([{main_name: "テーラードジャケット"},{main_name: "ノーカラージャケット"},{main_name: "Gジャン/デニムジャケット"},{main_name: "レザージャケット"},{main_name: "ダウンジャケット"},{main_name: "ライダースジャケット"},{main_name: "ミリタリージャケット"},{main_name: "ナイロンジャケット"},{main_name: "フライトジャケット"},{main_name: "ダッフルコート"},{main_name: "ピーコート"},{main_name: "ステンカラーコート"},{main_name: "トレンチコート"},{main_name: "モッズコート"},{main_name: "チェスターコート"},{main_name: "スタジャン"},{main_name: "スカジャン"},{main_name: "ブルゾン"},{main_name: "マウンテンパーカー"},{main_name: "ダウンベスト"},{main_name: "ポンチョ"},{main_name: "カバーオール"},{main_name: "その他"}])
men_pants = men.children.create(main_name: "パンツ")
men_pants.children.create([{main_name: "デニム/ジーンズ"},{main_name: "ワークパンツ/カーゴパンツ"},{main_name: "スラックス"},{main_name: "チノパン"},{main_name: "ショートパンツ"},{main_name: "ペインターパンツ"},{main_name: "サルエルパンツ"},{main_name: "オーバーオール"},{main_name: "その他"}])
men_shoes = men.children.create(main_name: "靴")
men_shoes.children.create([{main_name: "スニーカー"},{main_name: "サンダル"},{main_name: "ブーツ"},{main_name: "モカシン"},{main_name: "ドレス/ビジネス"},{main_name: "長靴/レインシューズ"},{main_name: "デッキシューズ"},{main_name: "その他"}])
men_bag = men.children.create(main_name: "バッグ")
men_bag.children.create([{main_name: "ショルダーバッグ"},{main_name: "トートバッグ"},{main_name: "ボストンバッグ"},{main_name: "リュック/バックパック"},{main_name: "ウエストポーチ"},{main_name: "ボディーバッグ"},{main_name: "ドラムバッグ"},{main_name: "ビジネスバッグ"},{main_name: "トラベルバッグ"},{main_name: "メッセンジャーバッグ"},{main_name: "エコバッグ"},{main_name: "その他"}])
men_suit = men.children.create(main_name: "スーツ")
men_suit.children.create([{main_name: "スーツジャケット"},{main_name: "スーツベスト"},{main_name: "スラックス"},{main_name: "セットアップ"},{main_name: "その他"}])
men_hat = men.children.create(main_name: "帽子")
men_hat.children.create([{main_name: "キャップ"},{main_name: "ハット"},{main_name: "ニットキャップ/ビーニー"},{main_name: "ハンチング/ベレー帽"},{main_name: "キャスケット"},{main_name: "サンバイザー"},{main_name: "その他"}])
men_jewelry = men.children.create(main_name: "アクセサリー")
men_jewelry.children.create([{main_name: "ネックレス"},{main_name: "ブレスレット"},{main_name: "バングル/リストバンド"},{main_name: "リング"},{main_name: "ピアス(片耳用)"},{main_name: "ピアス(両耳用)"},{main_name: "アンクレット"},{main_name: "その他"}])
men_accessories = men.children.create(main_name: "小物")
men_accessories.children.create([{main_name: "長財布"},{main_name: "折り財布"},{main_name: "マネークリップ"},{main_name: "コインケース/小銭入れ"},{main_name: "名刺入れ/定期入れ"},{main_name: "キーケース"},{main_name: "キーホルダー"},{main_name: "ネクタイ"},{main_name: "手袋"},{main_name: "ハンカチ"},{main_name: "ベルト"},{main_name: "マフラー"},{main_name: "ストール"},{main_name: "バンダナ"},{main_name: "ネックウォーマー"},{main_name: "サスペンダー"},{main_name: "ウォレットチェーン"},{main_name: "サングラス/メガネ"},{main_name: "モバイルケース/カバー"},{main_name: "手帳"},{main_name: "ストラップ"},{main_name: "ネクタイピン"},{main_name: "カフリンクス"},{main_name: "イヤマフラー"},{main_name: "傘"},{main_name: "レインコート"},{main_name: "ミラー"},{main_name: "タバコグッズ"},{main_name: "その他"}])
men_clock = men.children.create(main_name: "時計")
men_clock.children.create([{main_name: "腕時計(アナログ)"},{main_name: "腕時計(デジタル)"},{main_name: "ラバーベルト"},{main_name: "レザーベルト"},{main_name: "金属ベルト"},{main_name: "その他"}])
men_swimsuit = men.children.create(main_name: "水着")
men_swimsuit.children.create([{main_name: "一般水着"},{main_name: "スポーツ用"},{main_name: "アクセサリー"},{main_name: "その他"}])
men_legwear = men.children.create(main_name: "レッグウェア")
men_legwear.children.create([{main_name: "ソックス"},{main_name: "レギンス/スパッツ"},{main_name: "レッグウォーマー"},{main_name: "その他"}])
men_underwear = men.children.create(main_name: "アンダーウェア")
men_underwear.children.create([{main_name: "トランクス"},{main_name: "ボクサーパンツ"},{main_name: "その他"}])
men_other = men.children.create(main_name: "その他")
men_other.children.create([{main_name: "すべて"}])

# ベビー・キッズ
baby_kids = MainCategory.create(main_name: "ベビー・キッズ")
baby_kids_1 = baby_kids.children.create(main_name: "ベビー服(女の子用) ~95cm")
baby_kids_1.children.create([{main_name: "トップス"},{main_name: "アウター"},{main_name: "パンツ"},{main_name: "スカート"},{main_name: "ワンピース"},{main_name: "ベビードレス"},{main_name: "おくるみ"},{main_name: "下着/肌着"},{main_name: "パジャマ"},{main_name: "ロンパース"},{main_name: "その他"}])
baby_kids_2 = baby_kids.children.create(main_name: "ベビー服(男の子用) ~95cm")
baby_kids_2.children.create([{main_name: "トップス"},{main_name: "アウター"},{main_name: "パンツ"},{main_name: "おくるみ"},{main_name: "下着/肌着"},{main_name: "パジャマ"},{main_name: "ロンパース"},{main_name: "その他"}])
baby_kids_3 = baby_kids.children.create(main_name: "ベビー服(男女兼用) ~95cm")
baby_kids_3.children.create([{main_name: "トップス"},{main_name: "アウター"},{main_name: "パンツ"},{main_name: "おくるみ"},{main_name: "下着/肌着"},{main_name: "パジャマ"},{main_name: "ロンパース"},{main_name: "その他"}])
baby_kids_4 = baby_kids.children.create(main_name: "キッズ服(女の子用) 100cm~")
baby_kids_4.children.create([{main_name: "コート"},{main_name: "ジャケット/上着"},{main_name: "トップス(Tシャツ/カットソー)"},{main_name: "トップス(トレーナー)"},{main_name: "トップス(チュニック)"},{main_name: "トップス(タンクトップ)"},{main_name: "トップス(その他)"},{main_name: "スカート"},{main_name: "パンツ"},{main_name: "ワンピース"},{main_name: "セットアップ"},{main_name: "パジャマ"},{main_name: "フォーマル/ドレス"},{main_name: "和服"},{main_name: "浴衣"},{main_name: "甚平"},{main_name: "水着"},{main_name: "その他"}])
baby_kids_5 = baby_kids.children.create(main_name: "キッズ服(男の子用) 100cm~")
baby_kids_5.children.create([{main_name: "コート"},{main_name: "ジャケット/上着"},{main_name: "トップス(Tシャツ/カットソー)"},{main_name: "トップス(トレーナー)"},{main_name: "トップス(その他)"},{main_name: "パンツ"},{main_name: "セットアップ"},{main_name: "パジャマ"},{main_name: "フォーマル/ドレス"},{main_name: "和服"},{main_name: "浴衣"},{main_name: "甚平"},{main_name: "水着"},{main_name: "その他"}])
baby_kids_6 = baby_kids.children.create(main_name: "キッズ服(男女兼用) 100cm~")
baby_kids_6.children.create([{main_name: "コート"},{main_name: "ジャケット/上着"},{main_name: "トップス(Tシャツ/カットソー)"},{main_name: "トップス(トレーナー)"},{main_name: "トップス(その他)"},{main_name: "ボトムス"},{main_name: "パジャマ"},{main_name: "その他"}])
baby_kids_7 = baby_kids.children.create(main_name: "キッズ靴")
baby_kids_7.children.create([{main_name: "スニーカー"},{main_name: "サンダル"},{main_name: "ブーツ"},{main_name: "長靴"},{main_name: "その他"}])
baby_kids_8 = baby_kids.children.create(main_name: "子ども用ファッション小物")
baby_kids_8.children.create([{main_name: "靴下/スパッツ"},{main_name: "帽子"},{main_name: "エプロン"},{main_name: "サスペンダー"},{main_name: "タイツ"},{main_name: "ハンカチ"},{main_name: "バンダナ"},{main_name: "ベルト"},{main_name: "マフラー"},{main_name: "傘"},{main_name: "手袋"},{main_name: "スタイ"},{main_name: "バッグ"},{main_name: "その他"}])
baby_kids_9 = baby_kids.children.create(main_name: "おむつ/トイレ/バス")
baby_kids_9.children.create([{main_name: "おむつ用品"},{main_name: "おまる/補助便座"},{main_name: "トレーニングパンツ"},{main_name: "ベビーバス"},{main_name: "お風呂用品"},{main_name: "その他"}])
baby_kids_10 = baby_kids.children.create(main_name: "外出/移動用品")
baby_kids_10.children.create([{main_name: "ベビーカー"},{main_name: "抱っこひも/スリング"},{main_name: "チャイルドシート"},{main_name: "その他"}])
baby_kids_11 = baby_kids.children.create(main_name: "授乳/食事")
baby_kids_11.children.create([{main_name: "ミルク"},{main_name: "ベビーフード"},{main_name: "ベビー用食器"},{main_name: "その他"}])
baby_kids_12 = baby_kids.children.create(main_name: "ベビー家具/寝具/室内用品")
baby_kids_12.children.create([{main_name: "ベッド"},{main_name: "布団/毛布"},{main_name: "イス"},{main_name: "たんす"},{main_name: "その他"}])
baby_kids_13 = baby_kids.children.create(main_name: "おもちゃ")
baby_kids_13.children.create([{main_name: "おふろのおもちゃ"},{main_name: "がらがら"},{main_name: "オルゴール"},{main_name: "ベビージム"},{main_name: "手押し車/カタカタ"},{main_name: "知育玩具"},{main_name: "その他"}])
baby_kids_14 = baby_kids.children.create(main_name: "行事/記念品")
baby_kids_14.children.create([{main_name: "お宮参り用品"},{main_name: "お食い初め用品"},{main_name: "アルバム"},{main_name: "手形/足形"},{main_name: "その他"}])
baby_kids_15 = baby_kids.children.create(main_name: "その他")
baby_kids_15.children.create([{main_name: "母子手帳用品"},{main_name: "その他"}])

# インテリア・住まい・小物
interior_residence_accessory = MainCategory.create(main_name: "インテリア・住まい・小物")
interior_residence_accessory_1 = interior_residence_accessory.children.create(main_name: "キッチン/食器")
interior_residence_accessory_1.children.create([{main_name: "食器"},{main_name: "調理器具"},{main_name: "収納/キッチン雑貨"},{main_name: "弁当用品"},{main_name: "カトラリー(スプーン等)"},{main_name: "テーブル用品"},{main_name: "容器"},{main_name: "エプロン"},{main_name: "アルコールグッズ"},{main_name: "浄水機"},{main_name: "その他"}])
interior_residence_accessory_2 = interior_residence_accessory.children.create(main_name: "ベッド/マットレス")
interior_residence_accessory_2.children.create([{main_name: "セミシングルベッド"},{main_name: "シングルベッド"},{main_name: "セミダブルベッド"},{main_name: "ダブルベッド"},{main_name: "ワイドダブルベッド"},{main_name: "クイーンベッド"},{main_name: "キングベッド"},{main_name: "脚付きマットレスベッド"},{main_name: "マットレス"},{main_name: "すのこベッド"},{main_name: "ロフトベッド/システムベッド"},{main_name: "簡易ベッド/折りたたみベッド"},{main_name: "収納付き"},{main_name: "その他"}])
interior_residence_accessory_3 = interior_residence_accessory.children.create(main_name: "ソファ/ソファベッド")
interior_residence_accessory_3.children.create([{main_name: "ソファセット"},{main_name: "シングルソファ"},{main_name: "ラブソファ"},{main_name: "トリプルソファ"},{main_name: "オットマン"},{main_name: "コーナーソファ"},{main_name: "ビーズソファ/クッションソファ"},{main_name: "ローソファ/フロアソファ"},{main_name: "ソファベッド"},{main_name: "応接セット"},{main_name: "ソファカバー"},{main_name: "リクライニングソファ"},{main_name: "その他"}])
interior_residence_accessory_4 = interior_residence_accessory.children.create(main_name: "椅子/チェア")
interior_residence_accessory_4.children.create([{main_name: "一般"},{main_name: "スツール"},{main_name: "ダイニングチェア"},{main_name: "ハイバックチェア"},{main_name: "ロッキングチェア"},{main_name: "座椅子"},{main_name: "折り畳みイス"},{main_name: "デスクチェア"},{main_name: "その他"}])
interior_residence_accessory_5 = interior_residence_accessory.children.create(main_name: "机/テーブル")
interior_residence_accessory_5.children.create([{main_name: "こたつ"},{main_name: "カウンターテーブル"},{main_name: "サイドテーブル"},{main_name: "センターテーブル"},{main_name: "ダイニングテーブル"},{main_name: "座卓/ちゃぶ台"},{main_name: "アウトドア用"},{main_name: "パソコン用"},{main_name: "事務机/学習机"},{main_name: "その他"}])
interior_residence_accessory_6 = interior_residence_accessory.children.create(main_name: "収納家具")
interior_residence_accessory_6.children.create([{main_name: "リビング収納"},{main_name: "キッチン収納"},{main_name: "玄関/屋外収納"},{main_name: "バス/トイレ収納"},{main_name: "本収納"},{main_name: "本/CD/DVD収納"},{main_name: "洋服タンス/押入れ収納"},{main_name: "電話台/ファックス台"},{main_name: "ドレッサー/鏡台"},{main_name: "棚/ラック"},{main_name: "ケース/ボックス"},{main_name: "その他"}])
interior_residence_accessory_7 = interior_residence_accessory.children.create(main_name: "ラグ/カーペット/マット")
interior_residence_accessory_7.children.create([{main_name: "ラグ"},{main_name: "カーペット"},{main_name: "ホットカーペット"},{main_name: "玄関/キッチンマット"},{main_name: "トイレ/バスマット"},{main_name: "その他"}])
interior_residence_accessory_8 = interior_residence_accessory.children.create(main_name: "カーテン/ブラインド")
interior_residence_accessory_8.children.create([{main_name: "カーテン"},{main_name: "ブラインド"},{main_name: "ロールスクリーン"},{main_name: "のれん"},{main_name: "その他"}])
interior_residence_accessory_9 = interior_residence_accessory.children.create(main_name: "ライト/照明")
interior_residence_accessory_9.children.create([{main_name: "蛍光灯/電球"},{main_name: "天井照明"},{main_name: "フロアスタンド"},{main_name: "その他"}])
interior_residence_accessory_10 = interior_residence_accessory.children.create(main_name: "寝具")
interior_residence_accessory_10.children.create([{main_name: "布団/毛布"},{main_name: "枕"},{main_name: "シーツ/カバー"},{main_name: "その他"}])
interior_residence_accessory_11 = interior_residence_accessory.children.create(main_name: "インテリア小物")
interior_residence_accessory_11.children.create([{main_name: "ごみ箱"},{main_name: "ウェルカムボード"},{main_name: "オルゴール"},{main_name: "クッション"},{main_name: "クッションカバー"},{main_name: "スリッパラック"},{main_name: "ティッシュボックス"},{main_name: "バスケット/かご"},{main_name: "フォトフレーム"},{main_name: "マガジンラック"},{main_name: "モビール"},{main_name: "モビール"},{main_name: "花瓶"},{main_name: "灰皿"},{main_name: "傘立て"},{main_name: "小物入れ"},{main_name: "置時計"},{main_name: "掛時計/柱時計"},{main_name: "鏡(立て掛け式)"},{main_name: "鏡(壁掛け式)"},{main_name: "置物"},{main_name: "風鈴"},{main_name: "植物/観葉植物"},{main_name: "その他"}])
interior_residence_accessory_12 = interior_residence_accessory.children.create(main_name: "季節/年中行事")
interior_residence_accessory_12.children.create([{main_name: "正月"},{main_name: "成人式"},{main_name: "バレンタインデー"},{main_name: "ひな祭り"},{main_name: "子どもの日"},{main_name: "母の日"},{main_name: "父の日"},{main_name: "父の日"},{main_name: "サマーギフト/お中元"},{main_name: "夏/夏休み"},{main_name: "ハロウィン"},{main_name: "敬老の日"},{main_name: "七五三"},{main_name: "お歳暮"},{main_name: "クリスマス"},{main_name: "冬一般"},{main_name: "その他"}])
interior_residence_accessory_13 = interior_residence_accessory.children.create(main_name: "その他")
interior_residence_accessory_13.children.create([{main_name: "すべて"}])

# 本・音楽・ゲーム
book_music_game = MainCategory.create(main_name: "本・音楽・ゲーム")
book_music_game_1 = book_music_game.children.create(main_name: "本")
book_music_game_1.children.create([{main_name: "文学/小説"},{main_name: "人文/社会"},{main_name: "ノンフィクション/教養"},{main_name: "地図/旅行ガイド"},{main_name: "ビジネス/経済"},{main_name: "ビジネス/経済"},{main_name: "健康/医学"},{main_name: "コンピュータ/IT"},{main_name: "趣味/スポーツ/実用"},{main_name: "住まい/暮らし/子育て"},{main_name: "アート/エンタメ"},{main_name: "洋書"},{main_name: "絵本"},{main_name: "参考書"},{main_name: "その他"}])
book_music_game_2 = book_music_game.children.create(main_name: "漫画")
book_music_game_2.children.create([{main_name: "全巻セット"},{main_name: "少年漫画"},{main_name: "少女漫画"},{main_name: "青年漫画"},{main_name: "女性漫画"},{main_name: "同人誌"},{main_name: "その他"}])
book_music_game_3 = book_music_game.children.create(main_name: "雑誌")
book_music_game_3.children.create([{main_name: "アート/エンタメ/ホビー"},{main_name: "ファッション"},{main_name: "ニュース/総合"},{main_name: "趣味/スポーツ"},{main_name: "その他"}])
book_music_game_4 = book_music_game.children.create(main_name: "CD")
book_music_game_4.children.create([{main_name: "邦楽"},{main_name: "洋楽"},{main_name: "アニメ"},{main_name: "クラシック"},{main_name: "K-POP/アジア"},{main_name: "キッズ/ファミリー"},{main_name: "その他"}])
book_music_game_5 = book_music_game.children.create(main_name: "DVD/ブルーレイ")
book_music_game_5.children.create([{main_name: "外国映画"},{main_name: "日本映画"},{main_name: "アニメ"},{main_name: "TVドラマ"},{main_name: "ミュージック"},{main_name: "お笑い/バラエティ"},{main_name: "スポーツ/フィットネス"},{main_name: "キッズ/ファミリー"},{main_name: "その他"}])
book_music_game_6 = book_music_game.children.create(main_name: "レコード")
book_music_game_6.children.create([{main_name: "邦楽"},{main_name: "洋楽"},{main_name: "その他"}])
book_music_game_7 = book_music_game.children.create(main_name: "テレビゲーム")
book_music_game_7.children.create([{main_name: "家庭用ゲーム本体"},{main_name: "家庭用ゲームソフト"},{main_name: "携帯用ゲーム本体"},{main_name: "携帯用ゲームソフト"},{main_name: "PCゲーム"},{main_name: "その他"}])

# おもちゃ・ホビー・グッズ
toy_hobby_goods = MainCategory.create(main_name: "おもちゃ・ホビー・グッズ")
toy_hobby_goods_1 = toy_hobby_goods.children.create(main_name: "おもちゃ")
toy_hobby_goods_1.children.create([{main_name: "キャラクターグッズ"},{main_name: "ぬいぐるみ"},{main_name: "小物/アクセサリー"},{main_name: "模型/プラモデル"},{main_name: "ミニカー"},{main_name: "トイラジコン"},{main_name: "プラモデル"},{main_name: "ホビーラジコン"},{main_name: "鉄道模型"},{main_name: "その他"}])
toy_hobby_goods_2 = toy_hobby_goods.children.create(main_name: "タレントグッズ")
toy_hobby_goods_2.children.create([{main_name: "アイドル"},{main_name: "ミュージシャン"},{main_name: "タレント/お笑い芸人"},{main_name: "スポーツ選手"},{main_name: "その他"}])
toy_hobby_goods_3 = toy_hobby_goods.children.create(main_name: "コミック/アニメグッズ")
toy_hobby_goods_3.children.create([{main_name: "ストラップ"},{main_name: "キーホルダー"},{main_name: "バッジ"},{main_name: "カード"},{main_name: "クリアファイル"},{main_name: "ポスター"},{main_name: "タオル"},{main_name: "その他"}])
toy_hobby_goods_4 = toy_hobby_goods.children.create(main_name: "トレーディングカード")
toy_hobby_goods_4.children.create([{main_name: "遊戯王"},{main_name: "マジック：ザ・ギャザリング"},{main_name: "ポケモンカードゲーム"},{main_name: "デュエルマスターズ"},{main_name: "バトルスピリッツ"},{main_name: "プリパラ"},{main_name: "アイカツ"},{main_name: "カードファイト!! ヴァンガード"},{main_name: "ヴァイスシュヴァルツ"},{main_name: "プロ野球オーナーズリーグ"},{main_name: "ベースボールヒーローズ"},{main_name: "ドラゴンボール"},{main_name: "スリーブ"},{main_name: "その他"}])
toy_hobby_goods_5 = toy_hobby_goods.children.create(main_name: "フィギュア")
toy_hobby_goods_5.children.create([{main_name: "コミック/アニメ"},{main_name: "特撮"},{main_name: "ゲームキャラクター"},{main_name: "SF/ファンタジー/ホラー"},{main_name: "アメコミ"},{main_name: "スポーツ"},{main_name: "ミリタリー"},{main_name: "その他"}])
toy_hobby_goods_6 = toy_hobby_goods.children.create(main_name: "楽器/器材")
toy_hobby_goods_6.children.create([{main_name: "エレキギター"},{main_name: "アコースティックギター"},{main_name: "ベース"},{main_name: "エフェクター"},{main_name: "アンプ"},{main_name: "弦楽器"},{main_name: "管楽器"},{main_name: "鍵盤楽器"},{main_name: "打楽器"},{main_name: "和楽器"},{main_name: "楽譜/スコア"},{main_name: "レコーディング/PA機器"},{main_name: "DJ機器"},{main_name: "DTM/DAW"},{main_name: "その他"}])
toy_hobby_goods_7 = toy_hobby_goods.children.create(main_name: "コレクション")
toy_hobby_goods_7.children.create([{main_name: "武具"},{main_name: "使用済切手/官製はがき"},{main_name: "旧貨幣/金貨/銀貨/記念硬貨"},{main_name: "印刷物"},{main_name: "ノベルティグッズ"},{main_name: "その他"}])
toy_hobby_goods_8 = toy_hobby_goods.children.create(main_name: "ミリタリー")
toy_hobby_goods_8.children.create([{main_name: "トイガン"},{main_name: "個人装備"},{main_name: "その他"}])
toy_hobby_goods_9 = toy_hobby_goods.children.create(main_name: "美術品")
toy_hobby_goods_9.children.create([{main_name: "陶芸"},{main_name: "ガラス"},{main_name: "漆芸"},{main_name: "金属工芸"},{main_name: "絵画/タペストリ"},{main_name: "版画"},{main_name: "彫刻/オブジェクト"},{main_name: "書"},{main_name: "写真"},{main_name: "その他"}])
toy_hobby_goods_10 = toy_hobby_goods.children.create(main_name: "アート用品")
toy_hobby_goods_10.children.create([{main_name: "画材"},{main_name: "額縁"},{main_name: "その他"}])
toy_hobby_goods_11 = toy_hobby_goods.children.create(main_name: "その他")
toy_hobby_goods_11.children.create([{main_name: "トランプ/UNO"},{main_name: "カルタ/百人一首"},{main_name: "ダーツ"},{main_name: "ビリヤード"},{main_name: "麻雀"},{main_name: "パズル/ジグソーパズル"},{main_name: "囲碁/将棋"},{main_name: "オセロ/チェス"},{main_name: "人生ゲーム"},{main_name: "野球/サッカーゲーム"},{main_name: "スポーツ"},{main_name: "三輪車/乗り物"},{main_name: "ヨーヨー"},{main_name: "模型製作用品"},{main_name: "鉄道"},{main_name: "航空機"},{main_name: "アマチュア無線"},{main_name: "パチンコ/パチスロ"},{main_name: "その他"}])

# コスメ・香水・美容
cosme_perfume_beauty = MainCategory.create(main_name: "コスメ・香水・美容")
cosme_perfume_beauty_1 = cosme_perfume_beauty.children.create(main_name: "ベースメイク")
cosme_perfume_beauty_1.children.create([{main_name: "ファンデーション"},{main_name: "化粧下地"},{main_name: "コントロールカラー"},{main_name: "BBクリーム"},{main_name: "CCクリーム"},{main_name: "コンシーラー"},{main_name: "フェイスパウダー"},{main_name: "トライアルセット/サンプル"},{main_name: "その他"}])
cosme_perfume_beauty_2 = cosme_perfume_beauty.children.create(main_name: "メイクアップ")
cosme_perfume_beauty_2.children.create([{main_name: "アイシャドウ"},{main_name: "口紅"},{main_name: "リップグロス"},{main_name: "リップライナー"},{main_name: "チーク"},{main_name: "フェイスカラー"},{main_name: "マスカラ"},{main_name: "アイライナー"},{main_name: "つけまつげ"},{main_name: "アイブロウペンシル"},{main_name: "パウダーアイブロウ"},{main_name: "眉マスカラ"},{main_name: "トライアルセット/サンプル"},{main_name: "メイク道具/化粧小物"},{main_name: "美顔用品/美顔ローラー"},{main_name: "その他"}])
cosme_perfume_beauty_3 = cosme_perfume_beauty.children.create(main_name: "ネイルケア")
cosme_perfume_beauty_3.children.create([{main_name: "ネイルカラー"},{main_name: "カラージェル"},{main_name: "ネイルベースコート/トップコート"},{main_name: "ネイルアート用品"},{main_name: "ネイルパーツ"},{main_name: "ネイルチップ/付け爪"},{main_name: "手入れ用具"},{main_name: "除光液"},{main_name: "その他"}])
cosme_perfume_beauty_4 = cosme_perfume_beauty.children.create(main_name: "香水")
cosme_perfume_beauty_4.children.create([{main_name: "香水(女性用)"},{main_name: "香水(男性用)"},{main_name: "ユニセックス"},{main_name: "ボディミスト"},{main_name: "その他"}])
cosme_perfume_beauty_5 = cosme_perfume_beauty.children.create(main_name: "スキンケア/基礎化粧品")
cosme_perfume_beauty_5.children.create([{main_name: "化粧水/ローション"},{main_name: "乳液/ミルク"},{main_name: "美容液"},{main_name: "フェイスクリーム"},{main_name: "洗顔料"},{main_name: "クレンジング/メイク落とし"},{main_name: "パック/フェイスマスク"},{main_name: "ジェル/ゲル"},{main_name: "ブースター/導入液"},{main_name: "アイケア"},{main_name: "リップケア"},{main_name: "トライアルセット/サンプル"},{main_name: "洗顔グッズ"},{main_name: "その他"}])
cosme_perfume_beauty_6 = cosme_perfume_beauty.children.create(main_name: "ヘアケア")
cosme_perfume_beauty_6.children.create([{main_name: "シャンプー"},{main_name: "トリートメント"},{main_name: "コンディショナー"},{main_name: "リンス"},{main_name: "スタイリング剤"},{main_name: "カラーリング剤"},{main_name: "ブラシ"},{main_name: "その他"}])
cosme_perfume_beauty_7 = cosme_perfume_beauty.children.create(main_name: "ボディケア")
cosme_perfume_beauty_7.children.create([{main_name: "オイル/クリーム"},{main_name: "ハンドクリーム"},{main_name: "ローション"},{main_name: "日焼け止め/サンオイル"},{main_name: "ボディソープ"},{main_name: "入浴剤"},{main_name: "制汗/デオドラント"},{main_name: "フットケア"},{main_name: "その他"}])
cosme_perfume_beauty_8 = cosme_perfume_beauty.children.create(main_name: "オーラルケア")
cosme_perfume_beauty_8.children.create([{main_name: "口臭防止/エチケット用品"},{main_name: "歯ブラシ"},{main_name: "その他"}])
cosme_perfume_beauty_9 = cosme_perfume_beauty.children.create(main_name: "リラクゼーション")
cosme_perfume_beauty_9.children.create([{main_name: "エッセンシャルオイル"},{main_name: "芳香器"},{main_name: "お香/香炉"},{main_name: "キャンドル"},{main_name: "リラクゼーショングッズ"},{main_name: "その他"}])
cosme_perfume_beauty_10 = cosme_perfume_beauty.children.create(main_name: "ダイエット")
cosme_perfume_beauty_10.children.create([{main_name: "ダイエット食品"},{main_name: "エクササイズ用品"},{main_name: "体重計"},{main_name: "体脂肪計"},{main_name: "その他"}])
cosme_perfume_beauty_11 = cosme_perfume_beauty.children.create(main_name: "その他")
cosme_perfume_beauty_11.children.create([{main_name: "健康用品"},{main_name: "看護/介護用品"},{main_name: "救急/衛生用品"},{main_name: "その他"}])

# 家電・スマホ・カメラ
appliance_smartphone_camera = MainCategory.create(main_name: "家電・スマホ・カメラ")
appliance_smartphone_camera_1 = appliance_smartphone_camera.children.create(main_name: "スマートフォン/携帯電話")
appliance_smartphone_camera_1.children.create([{main_name: "スマートフォン本体"},{main_name: "バッテリー/充電器"},{main_name: "携帯電話本体"},{main_name: "PHS本体"},{main_name: "その他"}])
appliance_smartphone_camera_2 = appliance_smartphone_camera.children.create(main_name: "スマホアクセサリー")
appliance_smartphone_camera_2.children.create([{main_name: "Android用ケース"},{main_name: "iPhone用ケース"},{main_name: "カバー"},{main_name: "イヤホンジャック"},{main_name: "ストラップ"},{main_name: "フィルム"},{main_name: "自撮り棒"},{main_name: "その他"}])
appliance_smartphone_camera_3 = appliance_smartphone_camera.children.create(main_name: "PC/タブレット")
appliance_smartphone_camera_3.children.create([{main_name: "タブレット"},{main_name: "ノートPC"},{main_name: "デスクトップ型PC"},{main_name: "ディスプレイ"},{main_name: "電子ブックリーダー"},{main_name: "PC周辺機器"},{main_name: "PCパーツ"},{main_name: "その他"}])
appliance_smartphone_camera_4 = appliance_smartphone_camera.children.create(main_name: "カメラ")
appliance_smartphone_camera_4.children.create([{main_name: "デジタルカメラ"},{main_name: "ビデオカメラ"},{main_name: "レンズ(単焦点)"},{main_name: "レンズ(ズーム)"},{main_name: "フィルムカメラ"},{main_name: "防犯カメラ"},{main_name: "その他"}])
appliance_smartphone_camera_5 = appliance_smartphone_camera.children.create(main_name: "テレビ/映像機器")
appliance_smartphone_camera_5.children.create([{main_name: "テレビ"},{main_name: "プロジェクター"},{main_name: "ブルーレイレコーダー"},{main_name: "DVDレコーダー"},{main_name: "ブルーレイプレーヤー"},{main_name: "DVDプレーヤー"},{main_name: "映像用ケーブル"},{main_name: "その他"}])
appliance_smartphone_camera_6 = appliance_smartphone_camera.children.create(main_name: "オーディオ機器")
appliance_smartphone_camera_6.children.create([{main_name: "ポータブルプレーヤー"},{main_name: "イヤフォン"},{main_name: "ヘッドフォン"},{main_name: "アンプ"},{main_name: "スピーカー"},{main_name: "ケーブル/シールド"},{main_name: "ラジオ"},{main_name: "その他"}])
appliance_smartphone_camera_7 = appliance_smartphone_camera.children.create(main_name: "美容/健康")
appliance_smartphone_camera_7.children.create([{main_name: "ヘアドライヤー"},{main_name: "ヘアアイロン"},{main_name: "美容機器"},{main_name: "電気シェーバー"},{main_name: "電動歯ブラシ"},{main_name: "その他"}])
appliance_smartphone_camera_8 = appliance_smartphone_camera.children.create(main_name: "冷暖房/空調")
appliance_smartphone_camera_8.children.create([{main_name: "エアコン"},{main_name: "空気清浄器"},{main_name: "加湿器"},{main_name: "扇風機"},{main_name: "除湿機"},{main_name: "ファンヒーター"},{main_name: "電気ヒーター"},{main_name: "オイルヒーター"},{main_name: "ストーブ"},{main_name: "ホットカーペット"},{main_name: "こたつ"},{main_name: "電気毛布"},{main_name: "その他"}])
appliance_smartphone_camera_9 = appliance_smartphone_camera.children.create(main_name: "生活家電")
appliance_smartphone_camera_9.children.create([{main_name: "冷蔵庫"},{main_name: "洗濯機"},{main_name: "炊飯器"},{main_name: "電子レンジ/オーブン"},{main_name: "調理機器"},{main_name: "アイロン"},{main_name: "掃除機"},{main_name: "エスプレッソマシン"},{main_name: "コーヒーメーカー"},{main_name: "衣類乾燥機"},{main_name: "その他"}])
appliance_smartphone_camera_10 = appliance_smartphone_camera.children.create(main_name: "その他")
appliance_smartphone_camera_10.children.create([{main_name: "その他"}])
# スポーツ・レジャー
sport_leisure = MainCategory.create(main_name: "スポーツ・レジャー")
sport_leisure_1 = sport_leisure.children.create(main_name: "ゴルフ")
sport_leisure_1.children.create([{main_name: "クラブ"},{main_name: "ウエア(男性用)"},{main_name: "ウエア(女性用)"},{main_name: "バッグ"},{main_name: "シューズ(男性用)"},{main_name: "シューズ(女性用)"},{main_name: "アクセサリー"},{main_name: "その他"}])
sport_leisure_2 = sport_leisure.children.create(main_name: "フィッシング")
sport_leisure_2.children.create([{main_name: "ロッド"},{main_name: "リール"},{main_name: "ルアー用品"},{main_name: "ウエア"},{main_name: "釣り糸/ライン"},{main_name: "その他"}])
sport_leisure_3 = sport_leisure.children.create(main_name: "自転車")
sport_leisure_3.children.create([{main_name: "自転車本体"},{main_name: "ウエア"},{main_name: "パーツ"},{main_name: "アクセサリー"},{main_name: "バッグ"},{main_name: "工具/メンテナンス"},{main_name: "その他"}])
sport_leisure_4 = sport_leisure.children.create(main_name: "トレーニング/エクササイズ")
sport_leisure_4.children.create([{main_name: "ランニング"},{main_name: "ウォーキング"},{main_name: "ヨガ"},{main_name: "トレーニング用品"},{main_name: "その他"}])
sport_leisure_5 = sport_leisure.children.create(main_name: "野球")
sport_leisure_5.children.create([{main_name: "ウェア"},{main_name: "シューズ"},{main_name: "グローブ"},{main_name: "バット"},{main_name: "アクセサリー"},{main_name: "防具"},{main_name: "練習機器"},{main_name: "記念グッズ"},{main_name: "応援グッズ"},{main_name: "その他"}])
sport_leisure_6 = sport_leisure.children.create(main_name: "サッカー/フットサル")
sport_leisure_6.children.create([{main_name: "ウェア"},{main_name: "シューズ"},{main_name: "ボール"},{main_name: "アクセサリー"},{main_name: "記念グッズ"},{main_name: "応援グッズ"},{main_name: "その他"}])
sport_leisure_7 = sport_leisure.children.create(main_name: "テニス")
sport_leisure_7.children.create([{main_name: "ラケット(硬式用)"},{main_name: "ラケット(軟式用)"},{main_name: "ウェア"},{main_name: "シューズ"},{main_name: "ボール"},{main_name: "アクセサリー"},{main_name: "記念グッズ"},{main_name: "応援グッズ"},{main_name: "その他"}])
sport_leisure_8 = sport_leisure.children.create(main_name: "スノーボード")
sport_leisure_8.children.create([{main_name: "ボード"},{main_name: "バインディング"},{main_name: "ブーツ(男性用)"},{main_name: "ブーツ(女性用)"},{main_name: "ブーツ(子ども用)"},{main_name: "ウエア/装備(男性用)"},{main_name: "ウエア/装備(女性用)"},{main_name: "ウエア/装備(子ども用)"},{main_name: "アクセサリー"},{main_name: "バッグ"},{main_name: "その他"}])
sport_leisure_9 = sport_leisure.children.create(main_name: "スキー")
sport_leisure_9.children.create([{main_name: "板"},{main_name: "ブーツ(男性用)"},{main_name: "ブーツ(女性用)"},{main_name: "ブーツ(子ども用)"},{main_name: "ビンディング"},{main_name: "ウエア(男性用)"},{main_name: "ウエア(女性用)"},{main_name: "ウエア(子ども用)"},{main_name: "ストック"},{main_name: "その他"}])
sport_leisure_10 = sport_leisure.children.create(main_name: "その他スポーツ")
sport_leisure_10.children.create([{main_name: "ダンス/バレエ"},{main_name: "サーフィン"},{main_name: "バスケットボール"},{main_name: "バドミントン"},{main_name: "バレーボール"},{main_name: "スケートボード"},{main_name: "陸上競技"},{main_name: "ラグビー"},{main_name: "アメリカンフットボール"},{main_name: "ボクシング"},{main_name: "ボウリング"},{main_name: "その他"}])
sport_leisure_11 = sport_leisure.children.create(main_name: "アウトドア")
sport_leisure_11.children.create([{main_name: "テント/タープ"},{main_name: "ライト/ランタン"},{main_name: "寝袋/寝具"},{main_name: "テーブル/チェア"},{main_name: "ストーブ/コンロ"},{main_name: "調理器具"},{main_name: "食器"},{main_name: "登山用品"},{main_name: "その他"}])
sport_leisure_12 = sport_leisure.children.create(main_name: "その他")
sport_leisure_12.children.create([{main_name: "旅行用品"},{main_name: "その他"}])

# ハンドメイド
handmade = MainCategory.create(main_name: "ハンドメイド")
handmade_1 = handmade.children.create(main_name: "アクセサリー(女性用)")
handmade_1.children.create([{main_name: "ピアス"},{main_name: "イヤリング"},{main_name: "ネックレス"},{main_name: "ブレスレット"},{main_name: "リング"},{main_name: "チャーム"},{main_name: "ヘアゴム"},{main_name: "アンクレット"},{main_name: "その他"}])
handmade_2 = handmade.children.create(main_name: "ファッション/小物")
handmade_2.children.create([{main_name: "バッグ(女性用)"},{main_name: "バッグ(男性用)"},{main_name: "財布(女性用)"},{main_name: "財布(男性用)"},{main_name: "ファッション雑貨"},{main_name: "その他"}])
handmade_3 = handmade.children.create(main_name: "アクセサリー/時計")
handmade_3.children.create([{main_name: "アクセサリー(男性用)"},{main_name: "時計(女性用)"},{main_name: "時計(男性用)"},{main_name: "その他"}])
handmade_4 = handmade.children.create(main_name: "日用品/インテリア")
handmade_4.children.create([{main_name: "キッチン用品"},{main_name: "家具"},{main_name: "文房具"},{main_name: "アート/写真"},{main_name: "アロマ/キャンドル"},{main_name: "フラワー/ガーデン"},{main_name: "その他"}])
handmade_5 = handmade.children.create(main_name: "趣味/おもちゃ")
handmade_5.children.create([{main_name: "クラフト/布製品"},{main_name: "おもちゃ/人形"},{main_name: "その他"}])
handmade_6 = handmade.children.create(main_name: "キッズ/ベビー")
handmade_6.children.create([{main_name: "ファッション雑貨"},{main_name: "スタイ/よだれかけ"},{main_name: "外出用品"},{main_name: "ネームタグ"},{main_name: "その他"}])
handmade_7 = handmade.children.create(main_name: "素材/材料")
handmade_7.children.create([{main_name: "各種パーツ"},{main_name: "生地/糸"},{main_name: "型紙/パターン"},{main_name: "その他"}])
handmade_8 = handmade.children.create(main_name: "二次創作物")
handmade_8.children.create([{main_name: "Ingress"},{main_name: "クリエイターズ宇宙兄弟"},{main_name: "その他"},{main_name: "チケット"},{main_name: "すべて"}])
handmade_9 = handmade.children.create(main_name: "その他")
handmade_9.children.create([{main_name: "すべて"}])

# チケット
ticket = MainCategory.create(main_name: "チケット")
ticket_1 = ticket.children.create(main_name: "音楽")
ticket_1.children.create([{main_name: "男性アイドル"},{main_name: "女性アイドル"},{main_name: "韓流"},{main_name: "国内アーティスト"},{main_name: "海外アーティスト"},{main_name: "音楽フェス"},{main_name: "声優/アニメ"},{main_name: "その他"}])
ticket_2 = ticket.children.create(main_name: "スポーツ")
ticket_2.children.create([{main_name: "サッカー"},{main_name: "野球"},{main_name: "テニス"},{main_name: "格闘技/プロレス"},{main_name: "相撲/武道"},{main_name: "ゴルフ"},{main_name: "バレーボール"},{main_name: "バスケットボール"},{main_name: "モータースポーツ"},{main_name: "ウィンタースポーツ"},{main_name: "その他"}])
ticket_3 = ticket.children.create(main_name: "演劇/芸能")
ticket_3.children.create([{main_name: "ミュージカル"},{main_name: "演劇"},{main_name: "伝統芸能"},{main_name: "落語"},{main_name: "お笑い"},{main_name: "オペラ"},{main_name: "サーカス"},{main_name: "バレエ"},{main_name: "その他"}])
ticket_4 = ticket.children.create(main_name: "イベント")
ticket_4.children.create([{main_name: "声優/アニメ"},{main_name: "キッズ/ファミリー"},{main_name: "トークショー/講演会"},{main_name: "その他"}])
ticket_5 = ticket.children.create(main_name: "映画")
ticket_5.children.create([{main_name: "邦画"},{main_name: "洋画"},{main_name: "その他"}])
ticket_6 = ticket.children.create(main_name: "施設利用券")
ticket_6.children.create([{main_name: "遊園地/テーマパーク"},{main_name: "美術館/博物館"},{main_name: "スキー場"},{main_name: "ゴルフ場"},{main_name: "フィットネスクラブ"},{main_name: "プール"},{main_name: "ボウリング場"},{main_name: "水族館"},{main_name: "動物園"},{main_name: "その他"}])
ticket_7 = ticket.children.create(main_name: "優待券/割引券")
ticket_7.children.create([{main_name: "ショッピング"},{main_name: "レストラン/食事券"},{main_name: "フード/ドリンク券"},{main_name: "宿泊券"},{main_name: "その他"}])
ticket_8 = ticket.children.create(main_name: "その他")
ticket_8.children.create([{main_name: "すべて"}])


# 自動車・オートバイ
car_motorcycle = MainCategory.create(main_name: "自動車・オートバイ")
car_motorcycle_1 = car_motorcycle.children.create(main_name: "自動車本体")
car_motorcycle_1.children.create([{main_name: "国内自動車本体"},{main_name: "外国自動車本体"}])
car_motorcycle_2 = car_motorcycle.children.create(main_name: "自動車タイヤ/ホイール")
car_motorcycle_2.children.create([{main_name: "タイヤ/ホイールセット"},{main_name: "タイヤ"},{main_name: "ホイール"},{main_name: "その他"}])
car_motorcycle_3 = car_motorcycle.children.create(main_name: "自動車パーツ")
car_motorcycle_3.children.create([{main_name: "サスペンション"},{main_name: "ブレーキ"},{main_name: "外装、エアロパーツ"},{main_name: "ライト"},{main_name: "内装品、シート"},{main_name: "ステアリング"},{main_name: "マフラー・排気系"},{main_name: "エンジン、過給器、冷却装置"},{main_name: "クラッチ、ミッション、駆動系"},{main_name: "電装品"},{main_name: "補強パーツ"},{main_name: "汎用パーツ"},{main_name: "外国自動車用パーツ"},{main_name: "その他"}])
car_motorcycle_4 = car_motorcycle.children.create(main_name: "自動車アクセサリー")
car_motorcycle_4.children.create([{main_name: "車内アクセサリー"},{main_name: "カーナビ"},{main_name: "カーオーディオ"},{main_name: "車外アクセサリー"},{main_name: "メンテナンス用品"},{main_name: "チャイルドシート"},{main_name: "ドライブレコーダー"},{main_name: "レーダー探知機"},{main_name: "カタログ/マニュアル"},{main_name: "セキュリティ"},{main_name: "ETC"},{main_name: "その他"}])
car_motorcycle_5 = car_motorcycle.children.create(main_name: "オートバイ車体")
car_motorcycle_5.children.create([{main_name: "すべて"}])
car_motorcycle_6 = car_motorcycle.children.create(main_name: "オートバイパーツ")
car_motorcycle_6.children.create([{main_name: "タイヤ"},{main_name: "マフラー"},{main_name: "エンジン、冷却装置"},{main_name: "カウル、フェンダー、外装"},{main_name: "サスペンション"},{main_name: "ホイール"},{main_name: "シート"},{main_name: "ブレーキ"},{main_name: "タンク"},{main_name: "ライト、ウィンカー"},{main_name: "チェーン、スプロケット、駆動系"},{main_name: "メーター"},{main_name: "電装系"},{main_name: "ミラー"},{main_name: "外国オートバイ用パーツ"},{main_name: "その他"}])
car_motorcycle_7 = car_motorcycle.children.create(main_name: "オートバイアクセサリー")
car_motorcycle_7.children.create([{main_name: "ヘルメット/シールド"},{main_name: "バイクウエア/装備"},{main_name: "アクセサリー"},{main_name: "メンテナンス"},{main_name: "カタログ/マニュアル"},{main_name: "その他"}])

# その他
others = MainCategory.create(main_name: "その他")
others_1 = others.children.create(main_name: "まとめ売り")
others_1.children.create([{main_name: "すべて"}])
others_2 = others.children.create(main_name: "ペット用品")
others_2.children.create([{main_name: "ペットフード"},{main_name: "犬用品"},{main_name: "猫用品"},{main_name: "魚用品/水草"},{main_name: "小動物用品"},{main_name: "爬虫類/両生類用品"},{main_name: "かご/おり"},{main_name: "鳥用品"},{main_name: "虫類用品"},{main_name: "その他"}])
others_3 = others.children.create(main_name: "食品")
others_3.children.create([{main_name: "菓子"},{main_name: "米"},{main_name: "野菜"},{main_name: "果物"},{main_name: "調味料"},{main_name: "魚介類(加工食品)"},{main_name: "肉類(加工食品)"},{main_name: "その他 加工食品"},{main_name: "その他"}])
others_4 = others.children.create(main_name: "飲料/酒")
others_4.children.create([{main_name: "コーヒー"},{main_name: "ソフトドリンク"},{main_name: "ミネラルウォーター"},{main_name: "茶"},{main_name: "ウイスキー"},{main_name: "ワイン"},{main_name: "ブランデー"},{main_name: "焼酎"},{main_name: "日本酒"},{main_name: "ビール、発泡酒"},{main_name: "その他"}])
others_5 = others.children.create(main_name: "日用品/生活雑貨/旅行")
others_5.children.create([{main_name: "タオル/バス用品"},{main_name: "日用品/生活雑貨"},{main_name: "洗剤/柔軟剤"},{main_name: "旅行用品"},{main_name: "防災関連グッズ"},{main_name: "その他"}])
others_6 = others.children.create(main_name: "アンティーク/コレクション")
others_6.children.create([{main_name: "雑貨"},{main_name: "工芸品"},{main_name: "家具"},{main_name: "印刷物"},{main_name: "その他"}])
others_7 = others.children.create(main_name: "文房具/事務用品")
others_7.children.create([{main_name: "筆記具"},{main_name: "ノート/メモ帳"},{main_name: "テープ/マスキングテープ"},{main_name: "カレンダー/スケジュール"},{main_name: "アルバム/スクラップ"},{main_name: "ファイル/バインダー"},{main_name: "はさみ/カッター"},{main_name: "カードホルダー/名刺管理"},{main_name: "のり/ホッチキス"},{main_name: "その他"}])
others_8 = others.children.create(main_name: "事務/店舗用品")
others_8.children.create([{main_name: "オフィス用品一般"},{main_name: "オフィス家具"},{main_name: "店舗用品"},{main_name: "OA機器"},{main_name: "ラッピング/包装"},{main_name: "その他"}])
others_9 = others.children.create(main_name: "その他")
others_9.children.create([{main_name: "すべて"}])

